### ISSUE TITLE
posizione file in home assistant

### ISSUE THREAD

**Issue by Subia75** [calas80/Xiaomi-Vacuum-Package#2]
Buon giorno,
mi sto avvicinando ad home assistant e ho trovato questo pacchetto di integrazione.
purtroppo ho poche conoscenze di questo sistema e sto imparando ma non saprei esattamente dove mettere i vari file nelle cartelle corrette.
chiedo se possibile avere un aiuto sulla posizione corretta dove inserirli.
grazie e complimenti per l'integrazione.

**Comment by calas80** [comment]
Ciao! 
Vieni qui, avrai tutto l’aiuto che ti serve 

https://www.facebook.com/groups/147299622598134/?ref=share


Inviato da iPhone
